# The travis build script used to run the tests and deploy the code to npm
language: node_js
node_js:
  - v10
  - v8
  - v6

cache: npm

# Install dependencies
install: npm install

# Run the test and typescript test
script: npm run verify

